// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xnLQLW3oTtZcaDhHGdL2DVnETDnP3-I',
    appId: '1:347981347701:web:fac0eb66abad27f8f2313c',
    messagingSenderId: '347981347701',
    projectId: 'advocate-codeveer',
    authDomain: 'advocate-codeveer.firebaseapp.com',
    storageBucket: 'advocate-codeveer.appspot.com',
    measurementId: 'G-0YKKW9JP1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB4cg0OZsjIYWfP5v8E5Q-MmTiL_RNCGo',
    appId: '1:347981347701:android:e5f7af5723082058f2313c',
    messagingSenderId: '347981347701',
    projectId: 'advocate-codeveer',
    storageBucket: 'advocate-codeveer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZx0CbcbHfAxMXZJ3qXEaIV7egQDQlHw',
    appId: '1:347981347701:ios:401ba1888a05f32ef2313c',
    messagingSenderId: '347981347701',
    projectId: 'advocate-codeveer',
    storageBucket: 'advocate-codeveer.appspot.com',
    iosClientId: '347981347701-2lroaav1hq801sr1040d9gn6hmtlik1m.apps.googleusercontent.com',
    iosBundleId: 'net.codeveer.advocate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZx0CbcbHfAxMXZJ3qXEaIV7egQDQlHw',
    appId: '1:347981347701:ios:401ba1888a05f32ef2313c',
    messagingSenderId: '347981347701',
    projectId: 'advocate-codeveer',
    storageBucket: 'advocate-codeveer.appspot.com',
    iosClientId: '347981347701-2lroaav1hq801sr1040d9gn6hmtlik1m.apps.googleusercontent.com',
    iosBundleId: 'net.codeveer.advocate',
  );
}
